name: Docker packaging

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dockerBuild:
    name: Build & Push Docker Image

    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: 1.0.1

    steps:
    - uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Container build and push
      uses: docker/build-push-action@v2
      with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            zlatkoa/helloer:${{ env.RELEASE_TAG }}
