name: Build and Docker packaging

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - README.md
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - README.md

jobs:
  dockerBuild:
    name: Build & Push Docker Image

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: zlatko-ms/envarfiles@v3
      with:
        paths: ./package.json
        select: version

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 17
        
    - name: Execute Unit Tests
      run: |
        npm run app:init
        npm run app:test

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Container build and push
      uses: docker/build-push-action@v2
      with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            zlatkoa/helloer:${{ env.version }}
