name: Just Test

on:
  workflow_call:
  workflow_dispatch:

jobs:
  testing:
    name: Testing

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Read version
      uses: zlatko-ms/envarfiles@v2
      with:
        select: version
        paths: ./package.json
